# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/robocopy',
                'doc_host': 'https://agmontesb.github.io',
                'git_url': 'https://github.com/agmontesb/robocopy',
                'lib_path': 'robocopy'},
  'syms': {'robocopy.core': {'robocopy.core.foo': ('core.html#foo', 'robocopy/core.py')}}}
